// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repositories.Context;

#nullable disable

namespace Repositories.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251017193755_Added explicit Entity relationships")]
    partial class AddedexplicitEntityrelationships
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Repositories.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "7a9fd4e8-e423-4317-b7f0-027c52b9597c",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "310c4f3d-7260-4dbf-a724-1125396933af",
                            Email = "user1@test.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "USER1@TEST.COM",
                            NormalizedUserName = "USER1@TEST.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEGxzgP3stsGnt+Wjcj5DBA8dUozjCOsVFnYgzW2BGBbif/qjmJU+x3cvywyM27CmuQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "719b7447-7793-4675-9ee5-50f8980aeee7",
                            TwoFactorEnabled = false,
                            UserName = "user1@test.com"
                        },
                        new
                        {
                            Id = "64118f9c-e311-4aab-8554-5694cf3b40bd",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "38639097-f24e-4ebb-98fe-005a108a68f8",
                            Email = "user2@test.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "USER2@TEST.COM",
                            NormalizedUserName = "USER2@TEST.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAELZVGj0eWZFox6dqYlG3JLHadgQrVo32DKYytXxnyfLHqLeJEbbWVufVIwav0N6DiA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "8df7e20d-c88f-4194-8f1e-c9f095f917ed",
                            TwoFactorEnabled = false,
                            UserName = "user2@test.com"
                        });
                });

            modelBuilder.Entity("Repositories.Entities.IceCream", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("VendorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VendorId");

                    b.ToTable("IceCreamFlavors", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Premium vanilla with real bean specks",
                            Name = "Vanilla Bean Supreme",
                            Price = 3.99m,
                            VendorId = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "Rich chocolate ice cream with fudge swirls",
                            Name = "Double Chocolate Fudge",
                            Price = 4.49m,
                            VendorId = 1
                        },
                        new
                        {
                            Id = 3,
                            Description = "Fresh strawberry ice cream with real fruit pieces",
                            Name = "Strawberry Fields",
                            Price = 4.29m,
                            VendorId = 1
                        },
                        new
                        {
                            Id = 4,
                            Description = "Vanilla ice cream with chocolate cookie pieces",
                            Name = "Cookies and Cream",
                            Price = 4.39m,
                            VendorId = 1
                        },
                        new
                        {
                            Id = 5,
                            Description = "Buttery ice cream with candied pecans",
                            Name = "Butter Pecan",
                            Price = 4.59m,
                            VendorId = 1
                        },
                        new
                        {
                            Id = 6,
                            Description = "Authentic Italian pistachio gelato",
                            Name = "Pistachio Perfection",
                            Price = 5.99m,
                            VendorId = 2
                        },
                        new
                        {
                            Id = 7,
                            Description = "Coffee-flavored gelato with mascarpone swirl",
                            Name = "Tiramisu Delight",
                            Price = 5.99m,
                            VendorId = 2
                        },
                        new
                        {
                            Id = 8,
                            Description = "Cream gelato with fine chocolate shavings",
                            Name = "Stracciatella Classic",
                            Price = 5.49m,
                            VendorId = 2
                        },
                        new
                        {
                            Id = 9,
                            Description = "Smooth vanilla gelato with real bean specks",
                            Name = "Vanilla Bean",
                            Price = 5.29m,
                            VendorId = 2
                        },
                        new
                        {
                            Id = 10,
                            Description = "Rich chocolate gelato with hazelnut paste",
                            Name = "Chocolate Hazelnut",
                            Price = 5.79m,
                            VendorId = 2
                        },
                        new
                        {
                            Id = 11,
                            Description = "Refreshing mint with dark chocolate chips",
                            Name = "Mint Chip Madness",
                            Price = 4.79m,
                            VendorId = 3
                        },
                        new
                        {
                            Id = 12,
                            Description = "Vanilla ice cream loaded with cookie dough chunks",
                            Name = "Cookie Dough Blast",
                            Price = 4.99m,
                            VendorId = 3
                        },
                        new
                        {
                            Id = 13,
                            Description = "Creamy butterscotch with caramel swirls",
                            Name = "Butterscotch Ripple",
                            Price = 4.59m,
                            VendorId = 3
                        },
                        new
                        {
                            Id = 14,
                            Description = "Classic rich chocolate ice cream",
                            Name = "Chocolate",
                            Price = 4.29m,
                            VendorId = 3
                        },
                        new
                        {
                            Id = 15,
                            Description = "Traditional strawberry ice cream with real berries",
                            Name = "Strawberry",
                            Price = 4.39m,
                            VendorId = 3
                        },
                        new
                        {
                            Id = 16,
                            Description = "Caramel ice cream with sea salt and ribbon",
                            Name = "Salted Caramel Swirl",
                            Price = 5.29m,
                            VendorId = 4
                        },
                        new
                        {
                            Id = 17,
                            Description = "Cheesecake ice cream with mixed berry compote",
                            Name = "Berry Cheesecake",
                            Price = 5.49m,
                            VendorId = 4
                        },
                        new
                        {
                            Id = 18,
                            Description = "Maple ice cream with candied pecans",
                            Name = "Maple Pecan Crunch",
                            Price = 5.19m,
                            VendorId = 4
                        },
                        new
                        {
                            Id = 19,
                            Description = "Classic vanilla bean ice cream",
                            Name = "Vanilla",
                            Price = 4.89m,
                            VendorId = 4
                        },
                        new
                        {
                            Id = 20,
                            Description = "Peanut butter ice cream with chocolate cups",
                            Name = "Peanut Butter Cup",
                            Price = 5.39m,
                            VendorId = 4
                        },
                        new
                        {
                            Id = 21,
                            Description = "Delicate lavender ice cream with local honey",
                            Name = "Lavender Honey",
                            Price = 6.49m,
                            VendorId = 5
                        },
                        new
                        {
                            Id = 22,
                            Description = "Dark chocolate ice cream with orange zest",
                            Name = "Dark Chocolate Orange",
                            Price = 6.29m,
                            VendorId = 5
                        },
                        new
                        {
                            Id = 23,
                            Description = "Mascarpone ice cream with roasted figs",
                            Name = "Roasted Fig & Mascarpone",
                            Price = 6.99m,
                            VendorId = 5
                        },
                        new
                        {
                            Id = 24,
                            Description = "Premium artisan chocolate ice cream",
                            Name = "Chocolate",
                            Price = 5.99m,
                            VendorId = 5
                        },
                        new
                        {
                            Id = 25,
                            Description = "Vanilla ice cream infused with cardamom",
                            Name = "Cardamom Vanilla",
                            Price = 6.49m,
                            VendorId = 5
                        },
                        new
                        {
                            Id = 26,
                            Description = "Caramel ice cream with sea salt crystals",
                            Name = "Sea Salt Caramel",
                            Price = 5.49m,
                            VendorId = 6
                        },
                        new
                        {
                            Id = 27,
                            Description = "Creamy coconut ice cream with toasted coconut flakes",
                            Name = "Coconut Paradise",
                            Price = 5.29m,
                            VendorId = 6
                        },
                        new
                        {
                            Id = 28,
                            Description = "Tangy key lime ice cream with graham cracker pieces",
                            Name = "Key Lime Pie",
                            Price = 5.69m,
                            VendorId = 6
                        },
                        new
                        {
                            Id = 29,
                            Description = "Classic vanilla made with beach town charm",
                            Name = "Vanilla",
                            Price = 4.99m,
                            VendorId = 6
                        },
                        new
                        {
                            Id = 30,
                            Description = "Chocolate ice cream with marshmallows, nuts, and fudge",
                            Name = "Rocky Mountain Road",
                            Price = 5.79m,
                            VendorId = 7
                        },
                        new
                        {
                            Id = 31,
                            Description = "Mixed berry ice cream with granola clusters",
                            Name = "Wild Berry Trail",
                            Price = 5.49m,
                            VendorId = 7
                        },
                        new
                        {
                            Id = 32,
                            Description = "Graham cracker ice cream with chocolate and marshmallow",
                            Name = "Campfire S'mores",
                            Price = 5.99m,
                            VendorId = 7
                        },
                        new
                        {
                            Id = 33,
                            Description = "Rich mountain chocolate ice cream",
                            Name = "Chocolate",
                            Price = 5.29m,
                            VendorId = 7
                        },
                        new
                        {
                            Id = 34,
                            Description = "Sophisticated vanilla bean ice cream",
                            Name = "City Lights Vanilla",
                            Price = 5.99m,
                            VendorId = 8
                        },
                        new
                        {
                            Id = 35,
                            Description = "Coffee ice cream with chocolate espresso chips",
                            Name = "Espresso Chip",
                            Price = 6.29m,
                            VendorId = 8
                        },
                        new
                        {
                            Id = 36,
                            Description = "Ultra-rich chocolate ice cream",
                            Name = "Brownstone Chocolate",
                            Price = 6.19m,
                            VendorId = 8
                        },
                        new
                        {
                            Id = 37,
                            Description = "Fresh strawberry ice cream with urban flair",
                            Name = "Strawberry",
                            Price = 5.89m,
                            VendorId = 8
                        },
                        new
                        {
                            Id = 38,
                            Description = "Simple, pure vanilla ice cream",
                            Name = "Farm Fresh Vanilla",
                            Price = 4.29m,
                            VendorId = 9
                        },
                        new
                        {
                            Id = 39,
                            Description = "Old-fashioned chocolate ice cream",
                            Name = "Country Chocolate",
                            Price = 4.39m,
                            VendorId = 9
                        },
                        new
                        {
                            Id = 40,
                            Description = "Butter ice cream with fresh local pecans",
                            Name = "Butter Pecan",
                            Price = 4.59m,
                            VendorId = 9
                        },
                        new
                        {
                            Id = 41,
                            Description = "Classic strawberry made with local berries",
                            Name = "Strawberry",
                            Price = 4.49m,
                            VendorId = 9
                        },
                        new
                        {
                            Id = 42,
                            Description = "Traditional vanilla ice cream with a nostalgic taste",
                            Name = "Old-Fashioned Vanilla",
                            Price = 4.99m,
                            VendorId = 10
                        },
                        new
                        {
                            Id = 43,
                            Description = "Rich chocolate made the old-fashioned way",
                            Name = "Classic Chocolate",
                            Price = 4.99m,
                            VendorId = 10
                        },
                        new
                        {
                            Id = 44,
                            Description = "Strawberry ice cream with soda shop flair",
                            Name = "Strawberry Soda Float",
                            Price = 5.29m,
                            VendorId = 10
                        },
                        new
                        {
                            Id = 45,
                            Description = "Butter ice cream with toffee pieces",
                            Name = "Butter Brickle",
                            Price = 5.19m,
                            VendorId = 10
                        },
                        new
                        {
                            Id = 46,
                            Description = "Japanese matcha ice cream",
                            Name = "Matcha Green Tea",
                            Price = 6.49m,
                            VendorId = 11
                        },
                        new
                        {
                            Id = 47,
                            Description = "Indian-inspired chai tea ice cream",
                            Name = "Chai Spice",
                            Price = 6.29m,
                            VendorId = 11
                        },
                        new
                        {
                            Id = 48,
                            Description = "Thai-inspired mango ice cream with rice pudding swirl",
                            Name = "Mango Sticky Rice",
                            Price = 6.99m,
                            VendorId = 11
                        },
                        new
                        {
                            Id = 49,
                            Description = "Vanilla with global spice blend",
                            Name = "Vanilla Fusion",
                            Price = 5.99m,
                            VendorId = 11
                        },
                        new
                        {
                            Id = 50,
                            Description = "Organic vanilla bean ice cream",
                            Name = "Pure Vanilla Bean",
                            Price = 5.99m,
                            VendorId = 12
                        },
                        new
                        {
                            Id = 51,
                            Description = "Organic mixed berry ice cream",
                            Name = "Wild Berry Harvest",
                            Price = 6.29m,
                            VendorId = 12
                        },
                        new
                        {
                            Id = 52,
                            Description = "Organic fair-trade chocolate ice cream",
                            Name = "Dark Chocolate",
                            Price = 6.19m,
                            VendorId = 12
                        },
                        new
                        {
                            Id = 53,
                            Description = "Organic lavender ice cream with local honey",
                            Name = "Honey Lavender",
                            Price = 6.49m,
                            VendorId = 12
                        },
                        new
                        {
                            Id = 54,
                            Description = "Blue and pink cotton candy flavored ice cream",
                            Name = "Cotton Candy",
                            Price = 5.49m,
                            VendorId = 13
                        },
                        new
                        {
                            Id = 55,
                            Description = "Vanilla ice cream with funnel cake pieces",
                            Name = "Funnel Cake",
                            Price = 5.69m,
                            VendorId = 13
                        },
                        new
                        {
                            Id = 56,
                            Description = "Caramel ice cream with apple pie filling",
                            Name = "Caramel Apple",
                            Price = 5.79m,
                            VendorId = 13
                        },
                        new
                        {
                            Id = 57,
                            Description = "Chocolate and vanilla swirl with cone pieces",
                            Name = "Chocolate Dipped Cone",
                            Price = 5.59m,
                            VendorId = 13
                        },
                        new
                        {
                            Id = 58,
                            Description = "Extra rich chocolate for late-night studying",
                            Name = "Study Break Chocolate",
                            Price = 4.99m,
                            VendorId = 14
                        },
                        new
                        {
                            Id = 59,
                            Description = "Simple, comforting vanilla ice cream",
                            Name = "Dorm Room Vanilla",
                            Price = 4.79m,
                            VendorId = 14
                        },
                        new
                        {
                            Id = 60,
                            Description = "Coffee ice cream with chocolate-covered espresso beans",
                            Name = "Final Exam Coffee Crunch",
                            Price = 5.29m,
                            VendorId = 14
                        },
                        new
                        {
                            Id = 61,
                            Description = "Classic strawberry for college nostalgia",
                            Name = "Strawberry",
                            Price = 4.89m,
                            VendorId = 14
                        },
                        new
                        {
                            Id = 62,
                            Description = "Traditional vanilla made with historic recipe",
                            Name = "Heritage Vanilla",
                            Price = 5.49m,
                            VendorId = 15
                        },
                        new
                        {
                            Id = 63,
                            Description = "Chocolate ice cream from century-old recipe",
                            Name = "Founder's Chocolate",
                            Price = 5.49m,
                            VendorId = 15
                        },
                        new
                        {
                            Id = 64,
                            Description = "Strawberry ice cream with heritage berries",
                            Name = "Heirloom Strawberry",
                            Price = 5.69m,
                            VendorId = 15
                        },
                        new
                        {
                            Id = 65,
                            Description = "Classic butter pecan with family recipe",
                            Name = "Antique Butter Pecan",
                            Price = 5.79m,
                            VendorId = 15
                        });
                });

            modelBuilder.Entity("Repositories.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime>("OrderDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserId1")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("VendorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId1");

                    b.HasIndex("VendorId");

                    b.ToTable("Orders", (string)null);
                });

            modelBuilder.Entity("Repositories.Entities.OrderLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IceCreamId")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IceCreamId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderLines", (string)null);
                });

            modelBuilder.Entity("Repositories.Entities.Vendor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Website")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Vendors", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "123 Frost Street, Cooltown, CT 06510",
                            Email = "contact@icecreamparadise.com",
                            Name = "Ice Cream Paradise",
                            PhoneNumber = "555-0123",
                            Website = "www.icecreamparadise.com"
                        },
                        new
                        {
                            Id = 2,
                            Address = "456 Scoop Avenue, Freezeville, CT 06511",
                            Email = "info@gelatodreams.com",
                            Name = "Gelato Dreams",
                            PhoneNumber = "555-0124",
                            Website = "www.gelatodreams.com"
                        },
                        new
                        {
                            Id = 3,
                            Address = "789 Sundae Lane, Chillburg, CT 06512",
                            Email = "sales@frostysdelights.com",
                            Name = "Frosty's Delights",
                            PhoneNumber = "555-0125",
                            Website = "www.frostysdelights.com"
                        },
                        new
                        {
                            Id = 4,
                            Address = "321 Sugar Street, Sweetville, CT 06513",
                            Email = "hello@sweetscoops.com",
                            Name = "Sweet Scoops Creamery",
                            PhoneNumber = "555-0126",
                            Website = "www.sweetscoops.com"
                        },
                        new
                        {
                            Id = 5,
                            Address = "567 Cream Avenue, Artville, CT 06514",
                            Email = "info@artisanice.com",
                            Name = "Artisan Ice Works",
                            PhoneNumber = "555-0127",
                            Website = "www.artisanice.com"
                        },
                        new
                        {
                            Id = 6,
                            Address = "785 Beach Boulevard, Shoreline, CT 06515",
                            Email = "info@coastalcreamery.com",
                            Name = "Coastal Creamery",
                            PhoneNumber = "555-0128",
                            Website = "www.coastalcreamery.com"
                        },
                        new
                        {
                            Id = 7,
                            Address = "214 Summit Road, Highland, CT 06516",
                            Email = "contact@mountainpeakicecream.com",
                            Name = "Mountain Peak Ice Cream",
                            PhoneNumber = "555-0129",
                            Website = "www.mountainpeakicecream.com"
                        },
                        new
                        {
                            Id = 8,
                            Address = "433 Downtown Avenue, Cityville, CT 06517",
                            Email = "hello@urbanscoop.com",
                            Name = "Urban Scoop",
                            PhoneNumber = "555-0130",
                            Website = "www.urbanscoop.com"
                        },
                        new
                        {
                            Id = 9,
                            Address = "928 Milk Street, Farmtown, CT 06518",
                            Email = "sales@dairydelight.com",
                            Name = "Dairy Delight",
                            PhoneNumber = "555-0131",
                            Website = "www.dairydelight.com"
                        },
                        new
                        {
                            Id = 10,
                            Address = "356 Heritage Lane, Oldtown, CT 06519",
                            Email = "parlor@vintageicecream.com",
                            Name = "Vintage Ice Cream Parlor",
                            PhoneNumber = "555-0132",
                            Website = "www.vintageicecream.com"
                        },
                        new
                        {
                            Id = 11,
                            Address = "573 Fusion Boulevard, Innovation City, CT 06520",
                            Email = "info@fusionfrozen.com",
                            Name = "Fusion Frozen Treats",
                            PhoneNumber = "555-0133",
                            Website = "www.fusionfrozen.com"
                        },
                        new
                        {
                            Id = 12,
                            Address = "182 Organic Way, Greenvale, CT 06521",
                            Email = "hello@naturesscoop.com",
                            Name = "Nature's Scoop",
                            PhoneNumber = "555-0134",
                            Website = "www.naturesscoop.com"
                        },
                        new
                        {
                            Id = 13,
                            Address = "742 Festival Street, Funtown, CT 06522",
                            Email = "fun@carnivalcreamery.com",
                            Name = "Carnival Creamery",
                            PhoneNumber = "555-0135",
                            Website = "www.carnivalcreamery.com"
                        },
                        new
                        {
                            Id = 14,
                            Address = "105 Campus Drive, College Town, CT 06523",
                            Email = "campus@universityscoops.com",
                            Name = "University Scoops",
                            PhoneNumber = "555-0136",
                            Website = "www.universityscoops.com"
                        },
                        new
                        {
                            Id = 15,
                            Address = "481 Monument Square, Heritage City, CT 06524",
                            Email = "history@historiccreamery.com",
                            Name = "Historic Creamery",
                            PhoneNumber = "555-0137",
                            Website = "www.historiccreamery.com"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Repositories.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Repositories.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Repositories.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Repositories.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Repositories.Entities.IceCream", b =>
                {
                    b.HasOne("Repositories.Entities.Vendor", "Vendor")
                        .WithMany("IceCreamFlavors")
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("Repositories.Entities.Order", b =>
                {
                    b.HasOne("Repositories.Entities.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Repositories.Entities.Vendor", "Vendor")
                        .WithMany("Orders")
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("Repositories.Entities.OrderLine", b =>
                {
                    b.HasOne("Repositories.Entities.IceCream", "IceCream")
                        .WithMany("OrderLines")
                        .HasForeignKey("IceCreamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Repositories.Entities.Order", "Order")
                        .WithMany("OrderLines")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IceCream");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Repositories.Entities.IceCream", b =>
                {
                    b.Navigation("OrderLines");
                });

            modelBuilder.Entity("Repositories.Entities.Order", b =>
                {
                    b.Navigation("OrderLines");
                });

            modelBuilder.Entity("Repositories.Entities.Vendor", b =>
                {
                    b.Navigation("IceCreamFlavors");

                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
